eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        url: http://PAYMENT-SERVICE/payment/
  user-service:
    endpoints:
      fetchUserById:
        url: http://USER-SERVICE/user/

